### ISSUE TITLE
Cleanup data stored in the db that is useless

### ISSUE THREAD

**Issue by Mokita-J** [neiist-dev/neiist-website#19]
We never end up deleting any memberships or theses that might have expired.
Either modify the code or create a periodic SQL procedure to remove useless data.

**Comment by nelsontr** [comment]
There is currently no thesis in the database. Memberships shouldn't be deleted since GAC must know at all times who is and who was a member of NEIIST, in order to explain eventual problems of renovation timings. Data in the collaborators' table must not be deleted in order to check team changes and to have a history of NEIIST members.
